server:
  port: 5000

spring:
  application:
    name: crowd-project

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

# 阿里云OSS服务器相关配置
aliyun:
  oss:
    access-key-id: LTAI4GFBGZ5XvB8F8fUKkU4y
    access-key-secret: 8qbDQJjjFt1Wck8jnqdyXpm0BnCxoC
    bucket-domain: http://zzxcrowd210118.oss-cn-shanghai.aliyuncs.com
    bucket-name: zzxcrowd210118
    end-point: http://oss-cn-shanghai.aliyuncs.com

# 设置ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 1000
