server:
  port: 4000
spring:
  application:
    name: crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

# 阿里云短信接口的配置
crowd:
  sms:
    accessKeyId: LTAI4G9B9C2AMGB2uEuzxUEe  # 自己的accessKeyId
    accessKeySecret: msbaPM1IonpGNBcchjpgaBkRiVc5n6  # 自己的accessKeySecret
    signName: 乐优商城  # 签名名称
    verifyCodeTemplate: SMS_203672955  # 模板名称

# 设置ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 1000