server:
  port: 4000
spring:
  application:
    name: crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

# 阿里云短信接口的配置
crowd:
  sms:
    accessKeyId: LTAI4G2cBfjaAVrQrmSmgbiT  # 自己的accessKeyId
    accessKeySecret: mArtV6a9zP7cH3bI9XdM2Fi88s8ZdM  # 自己的accessKeySecret
    signName: 乐优商城  # 签名名称
    verifyCodeTemplate: SMS_203672955  # 模板名称