server:
  port: 1000  # 配置eureka的端口

spring:
  application:
    name: crowd-eureka  #服务名称

eureka:
  client:
    register-with-eureka: false   #自己无需将自己注册到eureka
    fetch-registry: false         #也无需从注册中心拉取服务
    service-url:
      defaultZone: http://localhost:1000/eureka
